### ISSUE TITLE
Can't search album if the account have too much albums.

### ISSUE THREAD

**Issue by meotimdihia** [3846masa/upload-gphotos#456]
Currently, I am using this code to get created album: 

![Code_2020-01-17_18-45-22](https://user-images.githubusercontent.com/300961/72610285-8dacb500-3959-11ea-88a2-1268b2135d52.png)

The `shareId` was got when I use official google photos API to share album and get its sharable link.

**Comment by 3846masa** [comment]
upload-gphotos cannot search a shared album that not be in albums section.
Please add a shared album to albums section. ( See https://support.google.com/photos/thread/199013?hl=en&msgid=199227 )

**Comment by meotimdihia** [comment]
I tried to search the album in the albums section. 
```
await gphotos.searchAlbum({ title: 'TestAlbum' });
```

Don't record it, but I think my account has 10000 albums.
And my code is work tried with new accounts.

**Comment by 3846masa** [comment]
Fixed to infinity loop when searching album is not found.
However, to search albums in 10000 albums needs 30sec ~ 1min.
So, I implemented `fetchAlbumById` method. Please use this method for getting album.

```ts
const album = await gphotos.fetchAlbumById({ id: 'XXXXX' });
await album.append(photo);
```

Try v4.2.0.

**Comment by meotimdihia** [comment]
Hi, thank for the update. I tested `fetchAlbumById`. It's work fine. But searchAlbum is still not working for me.
`https://github.com/3846masa/upload-gphotos/blob/1815e57c62c66706e6a74b3ad8c2548b8148ecff/src/GPhotos.ts#L82`

```javascript
const { results, nextCursor } = await this.fetchAlbumList({ cursor });
```
the variable `results` return empty in my case.
But if it's work and takes 30s ~ 1min to search, then I prefer to record ID and use method `FetchAlbumById` 😄.

**Comment by 3846masa** [comment]
Hmm...

Please check below and report it for finding out the reason.

- The value returned from the following code is same as the count of albums in https://photos.google.com/albums
    - ```ts
      const albumList = [];
      const cursor = null;
      do {
          const { results, nextCursor } = await this.fetchAlbumList({ cursor });
          albumList.push(...results);
          cursor = nextCursor;
      } while (cursor !== null);
      console.log(albumList.length);
      ```
- The key of request to fetch album info is "Z5xsfc".
    - First, access to https://photos.google.com/albums
    - Open Chrome devtools -> "Network" tab
    - Clear log and search "batchexecute"
    - Scroll down to fetch next album list
    - Check requests and report the key of request
    - **BE CAREFUL, DO NOT UPLOAD SCREENSHOT WITH AT VALUE WHEN YOU REPORT** ( "at" value is your private key, DO NOT UPLOAD IT)
    - Example: ![untitled](https://user-images.githubusercontent.com/5629366/72684514-7ff75b00-3b24-11ea-8ab6-e55cd131b4c9.png)

**Comment by meotimdihia** [comment]
Hi, this is my request and form data in network tab:  

![firefox_2020-01-19_23-52-37](https://user-images.githubusercontent.com/300961/72684864-cc3b9e80-3b16-11ea-9e45-7ac9cb82619e.png)
`Request URL:https://photos.google.com/_/PhotosUi/data/batchexecute?rpcids=Z5xsfc&f.sid=1697522859387238528&bl=boq_photosuiserver_20200116.12_p0&hl=vi&soc-app=165&soc-platform=1&soc-device=1&_reqid=2785366&rt=c`

`f.req: [[["Z5xsfc","[\"AH_uQ438pnU-mx_1fU5-1U5Qy6-xDMaVkzwx2mSGXJso1KWX86_cuMxHBbz4KV5ykBJHqbJkK_Va1XoTepPmMuTD5b61-BHKs_Y2QkUkYu2TkqkSVx3vpnd-BKRKfK6-kPm23ZYYxH2_-gvvFHLS9yFTKdXrWgb3GQ8ZGtWmLt-twPb7eKxkVRLKBeYnoWRE5YZsiB8urVmUvDJjfO6S092iaGcVF9dBoRxmU9TwunY0S9Kq6hqXqnbGwVWFeEEurKftbmZc_o8nEEju6TV0stELlboqifAjStl3xZFXpapNi-07UST1k60uYnrFuYkisRr0zCR0s6PgyyfvztDOOWwxeWk3wUyZP7JaAgRTJ_4n2Yq1GBB_unA\",null,null,null,1]",null,"generic"]]]
`

**Comment by 3846masa** [comment]
It seems to be same as in my environment... 🤔 

Could you try the following code? Is no albums returned?
```ts
const albumList = [];
const cursor = null;
do {
    const { results, nextCursor } = await gphotos.fetchAlbumList({ cursor });
    albumList.push(...results);
    cursor = nextCursor;
} while (cursor !== null);
console.log(albumList.length);
```

Or, Could you report response when you request via browser? (It maybe sensitive. I won't force that on you.)

**Comment by meotimdihia** [comment]
Hi, I tried the code: 
![Code_2020-01-20_08-41-48](https://user-images.githubusercontent.com/300961/72692850-beab0680-3b60-11ea-8ba2-1b306d4fbac2.png)
`albumList.length` return 0 

this is an example for response: https://gist.github.com/meotimdihia/471ecb42f9bd36e686c00162fa33b024 ( I modified link for privacy)

**Comment by 3846masa** [comment]
I read response but I dont know why the code cannot work....
I'm sorry I couldn't help you. :cry:

**Comment by meotimdihia** [comment]
In my case, I am fine with creating Album instance with albumId. I think It's faster too.
I would report again if I could find out the problem. Thanks 😀.
